//Application global config
const appUrl = "https://covid-19.tinhtd.info/";
const apiConfig = {
  totalDataEndpoint: "https://emag.thanhnien.vn/covid19/home/getSummPatient",
  cityDataEndpoint:"https://emag.thanhnien.vn/covid19/home/getAllPatientProvinces",
};
const aCityMaps = [
  {
    cityId: "VN-SG",
    cityName: "TP.HCM",
    clsconfirmed: "inc",
    clsdeaths: "",
    confirmed: 101747,
    incconfirmed: 1998,
    recovered: 367,
    deaths: 232,
    incdeath: 0,
    onevaccine: 1634236,
    donevaccine: 77613,
    onevaccinepercent: 18.17,
    donevaccinepercent: 0.86,
  },
  {
    cityId: "VN-57",
    cityName: "Bình Dương",
    clsconfirmed: "inc",
    clsdeaths: "",
    confirmed: 18315,
    incconfirmed: 519,
    recovered: 45,
    deaths: 0,
    incdeath: 0,
    onevaccine: 76598,
    donevaccine: 8045,
    onevaccinepercent: 3.16,
    donevaccinepercent: 0.33,
  },
  {
    cityId: "VN-41",
    cityName: "Long An",
    clsconfirmed: "inc",
    clsdeaths: "",
    confirmed: 6593,
    incconfirmed: 246,
    recovered: 8,
    deaths: 15,
    incdeath: 0,
    onevaccine: 105168,
    donevaccine: 20998,
    onevaccinepercent: 6.23,
    donevaccinepercent: 1.24,
  },
  {
    cityId: "VN-37",
    cityName: "Tây Ninh",
    clsconfirmed: "inc",
    clsdeaths: "",
    confirmed: 1825,
    incconfirmed: 176,
    recovered: 43,
    deaths: 1,
    incdeath: 0,
    onevaccine: 40885,
    donevaccine: 1831,
    onevaccinepercent: 3.5,
    donevaccinepercent: 0.16,
  },
  {
    cityId: "VN-39",
    cityName: "Đồng Nai",
    clsconfirmed: "inc",
    clsdeaths: "",
    confirmed: 5191,
    incconfirmed: 147,
    recovered: 28,
    deaths: 0,
    incdeath: 0,
    onevaccine: 60509,
    donevaccine: 17281,
    onevaccinepercent: 1.95,
    donevaccinepercent: 0.56,
  },
  {
    cityId: "VN-49",
    cityName: "Vĩnh Long",
    clsconfirmed: "inc",
    clsdeaths: "",
    confirmed: 974,
    incconfirmed: 72,
    recovered: 7,
    deaths: 0,
    incdeath: 0,
    onevaccine: 39191,
    donevaccine: 4807,
    onevaccinepercent: 3.83,
    donevaccinepercent: 0.47,
  },
  {
    cityId: "VN-40",
    cityName: "Bình Thuận",
    clsconfirmed: "inc",
    clsdeaths: "",
    confirmed: 760,
    incconfirmed: 72,
    recovered: 10,
    deaths: 0,
    incdeath: 0,
    onevaccine: 35063,
    donevaccine: 812,
    onevaccinepercent: 2.85,
    donevaccinepercent: 0.07,
  },
  {
    cityId: "VN-DN",
    cityName: "Đà Nẵng",
    clsconfirmed: "inc",
    clsdeaths: "",
    confirmed: 1591,
    incconfirmed: 66,
    recovered: 532,
    deaths: 34,
    incdeath: 0,
    onevaccine: 47890,
    donevaccine: 3248,
    onevaccinepercent: 4.22,
    donevaccinepercent: 0.29,
  },
  {
    cityId: "VN-50",
    cityName: "Bến Tre",
    clsconfirmed: "inc",
    clsdeaths: "",
    confirmed: 866,
    incconfirmed: 62,
    recovered: 3,
    deaths: 0,
    incdeath: 0,
    onevaccine: 47852,
    donevaccine: 17142,
    onevaccinepercent: 3.71,
    donevaccinepercent: 1.33,
  },
  {
    cityId: "VN-52",
    cityName: "Sóc Trăng",
    clsconfirmed: "inc",
    clsdeaths: "",
    confirmed: 223,
    incconfirmed: 33,
    recovered: 0,
    deaths: 0,
    incdeath: 0,
    onevaccine: 38064,
    donevaccine: 19100,
    onevaccinepercent: 3.17,
    donevaccinepercent: 1.59,
  },
  {
    cityId: "VN-45",
    cityName: "Đồng Tháp",
    clsconfirmed: "inc",
    clsdeaths: "",
    confirmed: 3290,
    incconfirmed: 31,
    recovered: 27,
    deaths: 29,
    incdeath: 0,
    onevaccine: 136506,
    donevaccine: 21461,
    onevaccinepercent: 8.53,
    donevaccinepercent: 1.34,
  },
  {
    cityId: "VN-CT",
    cityName: "Cần Thơ",
    clsconfirmed: "inc",
    clsdeaths: "",
    confirmed: 1185,
    incconfirmed: 31,
    recovered: 33,
    deaths: 0,
    incdeath: 0,
    onevaccine: 52927,
    donevaccine: 7842,
    onevaccinepercent: 4.28,
    donevaccinepercent: 0.63,
  },
  {
    cityId: "VN-44",
    cityName: "An Giang",
    clsconfirmed: "inc",
    clsdeaths: "",
    confirmed: 391,
    incconfirmed: 26,
    recovered: 5,
    deaths: 0,
    incdeath: 0,
    onevaccine: 75035,
    donevaccine: 8096,
    onevaccinepercent: 3.93,
    donevaccinepercent: 0.42,
  },
  {
    cityId: "VN-32",
    cityName: "Phú Yên",
    clsconfirmed: "inc",
    clsdeaths: "",
    confirmed: 1611,
    incconfirmed: 20,
    recovered: 28,
    deaths: 0,
    incdeath: 0,
    onevaccine: 44702,
    donevaccine: 7203,
    onevaccinepercent: 4.65,
    donevaccinepercent: 0.75,
  },
  {
    cityId: "VN-31",
    cityName: "Bình Định",
    clsconfirmed: "inc",
    clsdeaths: "",
    confirmed: 239,
    incconfirmed: 18,
    recovered: 1,
    deaths: 0,
    incdeath: 0,
    onevaccine: 50179,
    donevaccine: 11171,
    onevaccinepercent: 3.37,
    donevaccinepercent: 0.75,
  },
  {
    cityId: "VN-33",
    cityName: "Đắk Lắk",
    clsconfirmed: "inc",
    clsdeaths: "",
    confirmed: 268,
    incconfirmed: 11,
    recovered: 3,
    deaths: 0,
    incdeath: 0,
    onevaccine: 58138,
    donevaccine: 16047,
    onevaccinepercent: 3.11,
    donevaccinepercent: 0.86,
  },
  {
    cityId: "VN-72",
    cityName: "Đắk Nông",
    clsconfirmed: "inc",
    clsdeaths: "",
    confirmed: 90,
    incconfirmed: 8,
    recovered: 0,
    deaths: 0,
    incdeath: 0,
    onevaccine: 32297,
    donevaccine: 1947,
    onevaccinepercent: 5.19,
    donevaccinepercent: 0.31,
  },
  {
    cityId: "VN-22",
    cityName: "Nghệ An",
    clsconfirmed: "inc",
    clsdeaths: "",
    confirmed: 243,
    incconfirmed: 5,
    recovered: 4,
    deaths: 0,
    incdeath: 0,
    onevaccine: 52193,
    donevaccine: 24260,
    onevaccinepercent: 1.57,
    donevaccinepercent: 0.73,
  },
  {
    cityId: "VN-23",
    cityName: "Hà Tĩnh",
    clsconfirmed: "inc",
    clsdeaths: "",
    confirmed: 177,
    incconfirmed: 4,
    recovered: 8,
    deaths: 0,
    incdeath: 0,
    onevaccine: 39862,
    donevaccine: 10318,
    onevaccinepercent: 3.09,
    donevaccinepercent: 0.8,
  },
  {
    cityId: "VN-47",
    cityName: "Kiên Giang",
    clsconfirmed: "inc",
    clsdeaths: "",
    confirmed: 362,
    incconfirmed: 3,
    recovered: 3,
    deaths: 0,
    incdeath: 0,
    onevaccine: 73169,
    donevaccine: 10297,
    onevaccinepercent: 4.25,
    donevaccinepercent: 0.6,
  },
  {
    cityId: "VN-55",
    cityName: "Bạc Liêu",
    clsconfirmed: "inc",
    clsdeaths: "",
    confirmed: 86,
    incconfirmed: 3,
    recovered: 53,
    deaths: 0,
    incdeath: 0,
    onevaccine: 27648,
    donevaccine: 8365,
    onevaccinepercent: 3.05,
    donevaccinepercent: 0.92,
  },
  {
    cityId: "VN-05",
    cityName: "Sơn La",
    clsconfirmed: "inc",
    clsdeaths: "",
    confirmed: 22,
    incconfirmed: 3,
    recovered: 0,
    deaths: 0,
    incdeath: 0,
    onevaccine: 45801,
    donevaccine: 4202,
    onevaccinepercent: 3.67,
    donevaccinepercent: 0.34,
  },
  {
    cityId: "VN-68",
    cityName: "Phú Thọ",
    clsconfirmed: "inc",
    clsdeaths: "",
    confirmed: 16,
    incconfirmed: 3,
    recovered: 3,
    deaths: 0,
    incdeath: 0,
    onevaccine: 42716,
    donevaccine: 10068,
    onevaccinepercent: 2.92,
    donevaccinepercent: 0.69,
  },
  {
    cityId: "VN-61",
    cityName: "Hải Dương",
    clsconfirmed: "inc",
    clsdeaths: "",
    confirmed: 846,
    incconfirmed: 2,
    recovered: 794,
    deaths: 0,
    incdeath: 0,
    onevaccine: 106354,
    donevaccine: 18716,
    onevaccinepercent: 5.62,
    donevaccinepercent: 0.99,
  },
  {
    cityId: "VN-HN",
    cityName: "Hà Nội",
    clsconfirmed: "inc",
    clsdeaths: "",
    confirmed: 1878,
    incconfirmed: 1,
    recovered: 395,
    deaths: 20,
    incdeath: 0,
    onevaccine: 780561,
    donevaccine: 58274,
    onevaccinepercent: 9.69,
    donevaccinepercent: 0.72,
  },
  {
    cityId: "VN-21",
    cityName: "Thanh Hóa",
    clsconfirmed: "inc",
    clsdeaths: "",
    confirmed: 110,
    incconfirmed: 1,
    recovered: 26,
    deaths: 0,
    incdeath: 0,
    onevaccine: 48065,
    donevaccine: 2382,
    onevaccinepercent: 1.32,
    donevaccinepercent: 0.07,
  },
  {
    cityId: "VN-71",
    cityName: "Điện Biên",
    clsconfirmed: "inc",
    clsdeaths: "",
    confirmed: 60,
    incconfirmed: 1,
    recovered: 15,
    deaths: 0,
    incdeath: 0,
    onevaccine: 53191,
    donevaccine: 8088,
    onevaccinepercent: 8.88,
    donevaccinepercent: 1.35,
  },
  {
    cityId: "VN-25",
    cityName: "Quảng Trị",
    clsconfirmed: "inc",
    clsdeaths: "",
    confirmed: 27,
    incconfirmed: 1,
    recovered: 9,
    deaths: 1,
    incdeath: 0,
    onevaccine: 19805,
    donevaccine: 4959,
    onevaccinepercent: 3.13,
    donevaccinepercent: 0.78,
  },
  {
    cityId: "VN-54",
    cityName: "Bắc Giang",
    clsconfirmed: "",
    clsdeaths: "",
    confirmed: 5960,
    incconfirmed: 0,
    recovered: 1618,
    deaths: 12,
    incdeath: 0,
    onevaccine: 274033,
    donevaccine: 20072,
    onevaccinepercent: 15.19,
    donevaccinepercent: 1.11,
  },
  {
    cityId: "VN-34",
    cityName: "Khánh Hòa",
    clsconfirmed: "",
    clsdeaths: "",
    confirmed: 2530,
    incconfirmed: 0,
    recovered: 113,
    deaths: 0,
    incdeath: 0,
    onevaccine: 40806,
    donevaccine: 2529,
    onevaccinepercent: 3.31,
    donevaccinepercent: 0.21,
  },
  {
    cityId: "VN-46",
    cityName: "Tiền Giang",
    clsconfirmed: "",
    clsdeaths: "",
    confirmed: 2348,
    incconfirmed: 0,
    recovered: 4,
    deaths: 1,
    incdeath: 0,
    onevaccine: 51727,
    donevaccine: 14346,
    onevaccinepercent: 2.93,
    donevaccinepercent: 0.81,
  },
  {
    cityId: "VN-56",
    cityName: "Bắc Ninh",
    clsconfirmed: "",
    clsdeaths: "",
    confirmed: 1755,
    incconfirmed: 0,
    recovered: 702,
    deaths: 12,
    incdeath: 0,
    onevaccine: 278080,
    donevaccine: 22546,
    onevaccinepercent: 20.32,
    donevaccinepercent: 1.65,
  },
  {
    cityId: "VN-43",
    cityName: "Bà Rịa - Vũng Tàu",
    clsconfirmed: "",
    clsdeaths: "",
    confirmed: 1525,
    incconfirmed: 0,
    recovered: 110,
    deaths: 0,
    incdeath: 0,
    onevaccine: 39567,
    donevaccine: 870,
    onevaccinepercent: 3.45,
    donevaccinepercent: 0.08,
  },
  {
    cityId: "VN-51",
    cityName: "Trà Vinh",
    clsconfirmed: "",
    clsdeaths: "",
    confirmed: 379,
    incconfirmed: 0,
    recovered: 8,
    deaths: 0,
    incdeath: 0,
    onevaccine: 28531,
    donevaccine: 0,
    onevaccinepercent: 2.83,
    donevaccinepercent: 0.0,
  },
  {
    cityId: "VN-29",
    cityName: "Quảng Ngãi",
    clsconfirmed: "",
    clsdeaths: "",
    confirmed: 296,
    incconfirmed: 0,
    recovered: 7,
    deaths: 0,
    incdeath: 0,
    onevaccine: 44568,
    donevaccine: 7659,
    onevaccinepercent: 3.62,
    donevaccinepercent: 0.62,
  },
  {
    cityId: "VN-66",
    cityName: "Hưng Yên",
    clsconfirmed: "",
    clsdeaths: "",
    confirmed: 295,
    incconfirmed: 0,
    recovered: 53,
    deaths: 0,
    incdeath: 0,
    onevaccine: 45651,
    donevaccine: 8629,
    onevaccinepercent: 3.64,
    donevaccinepercent: 0.69,
  },
  {
    cityId: "VN-27",
    cityName: "Quảng Nam",
    clsconfirmed: "",
    clsdeaths: "",
    confirmed: 276,
    incconfirmed: 0,
    recovered: 109,
    deaths: 3,
    incdeath: 0,
    onevaccine: 42722,
    donevaccine: 10609,
    onevaccinepercent: 2.86,
    donevaccinepercent: 0.71,
  },
  {
    cityId: "VN-58",
    cityName: "Bình Phước",
    clsconfirmed: "",
    clsdeaths: "",
    confirmed: 239,
    incconfirmed: 0,
    recovered: 0,
    deaths: 0,
    incdeath: 0,
    onevaccine: 46060,
    donevaccine: 16346,
    onevaccinepercent: 4.63,
    donevaccinepercent: 1.64,
  },
  {
    cityId: "VN-70",
    cityName: "Vĩnh Phúc",
    clsconfirmed: "",
    clsdeaths: "",
    confirmed: 237,
    incconfirmed: 0,
    recovered: 42,
    deaths: 0,
    incdeath: 0,
    onevaccine: 27496,
    donevaccine: 6971,
    onevaccinepercent: 2.38,
    donevaccinepercent: 0.6,
  },
  {
    cityId: "VN-36",
    cityName: "Ninh Thuận",
    clsconfirmed: "",
    clsdeaths: "",
    confirmed: 232,
    incconfirmed: 0,
    recovered: 11,
    deaths: 0,
    incdeath: 0,
    onevaccine: 38453,
    donevaccine: 2591,
    onevaccinepercent: 6.51,
    donevaccinepercent: 0.44,
  },
  {
    cityId: "VN-73",
    cityName: "Hậu Giang",
    clsconfirmed: "",
    clsdeaths: "",
    confirmed: 228,
    incconfirmed: 0,
    recovered: 0,
    deaths: 0,
    incdeath: 0,
    onevaccine: 23233,
    donevaccine: 4181,
    onevaccinepercent: 3.17,
    donevaccinepercent: 0.57,
  },
  {
    cityId: "VN-09",
    cityName: "Lạng Sơn",
    clsconfirmed: "",
    clsdeaths: "",
    confirmed: 132,
    incconfirmed: 0,
    recovered: 10,
    deaths: 1,
    incdeath: 0,
    onevaccine: 76856,
    donevaccine: 10494,
    onevaccinepercent: 9.83,
    donevaccinepercent: 1.34,
  },
  {
    cityId: "VN-13",
    cityName: "Quảng Ninh",
    clsconfirmed: "",
    clsdeaths: "",
    confirmed: 104,
    incconfirmed: 0,
    recovered: 78,
    deaths: 0,
    incdeath: 0,
    onevaccine: 120230,
    donevaccine: 13379,
    onevaccinepercent: 9.11,
    donevaccinepercent: 1.01,
  },
  {
    cityId: "VN-30",
    cityName: "Gia Lai",
    clsconfirmed: "",
    clsdeaths: "",
    confirmed: 89,
    incconfirmed: 0,
    recovered: 26,
    deaths: 0,
    incdeath: 0,
    onevaccine: 62724,
    donevaccine: 1033,
    onevaccinepercent: 4.14,
    donevaccinepercent: 0.07,
  },
  {
    cityId: "VN-20",
    cityName: "Thái Bình",
    clsconfirmed: "",
    clsdeaths: "",
    confirmed: 79,
    incconfirmed: 0,
    recovered: 41,
    deaths: 0,
    incdeath: 0,
    onevaccine: 33493,
    donevaccine: 3352,
    onevaccinepercent: 1.8,
    donevaccinepercent: 0.18,
  },
  {
    cityId: "VN-18",
    cityName: "Ninh Bình",
    clsconfirmed: "",
    clsdeaths: "",
    confirmed: 74,
    incconfirmed: 0,
    recovered: 36,
    deaths: 0,
    incdeath: 0,
    onevaccine: 27002,
    donevaccine: 465,
    onevaccinepercent: 2.75,
    donevaccinepercent: 0.05,
  },
  {
    cityId: "VN-63",
    cityName: "Hà Nam",
    clsconfirmed: "",
    clsdeaths: "",
    confirmed: 73,
    incconfirmed: 0,
    recovered: 25,
    deaths: 0,
    incdeath: 0,
    onevaccine: 33985,
    donevaccine: 6839,
    onevaccinepercent: 3.99,
    donevaccinepercent: 0.8,
  },
  {
    cityId: "VN-26",
    cityName: "Thừa Thiên Huế",
    clsconfirmed: "",
    clsdeaths: "",
    confirmed: 67,
    incconfirmed: 0,
    recovered: 6,
    deaths: 0,
    incdeath: 0,
    onevaccine: 44768,
    donevaccine: 5574,
    onevaccinepercent: 3.97,
    donevaccinepercent: 0.49,
  },
  {
    cityId: "VN-35",
    cityName: "Lâm Đồng",
    clsconfirmed: "",
    clsdeaths: "",
    confirmed: 52,
    incconfirmed: 0,
    recovered: 0,
    deaths: 0,
    incdeath: 0,
    onevaccine: 52514,
    donevaccine: 8260,
    onevaccinepercent: 4.05,
    donevaccinepercent: 0.64,
  },
  {
    cityId: "VN-14",
    cityName: "Hòa Bình",
    clsconfirmed: "",
    clsdeaths: "",
    confirmed: 45,
    incconfirmed: 0,
    recovered: 0,
    deaths: 0,
    incdeath: 0,
    onevaccine: 27611,
    donevaccine: 4990,
    onevaccinepercent: 3.23,
    donevaccinepercent: 0.58,
  },
  {
    cityId: "VN-HP",
    cityName: "Hải Phòng",
    clsconfirmed: "",
    clsdeaths: "",
    confirmed: 38,
    incconfirmed: 0,
    recovered: 10,
    deaths: 0,
    incdeath: 0,
    onevaccine: 59745,
    donevaccine: 7476,
    onevaccinepercent: 3.25,
    donevaccinepercent: 0.41,
  },
  {
    cityId: "VN-59",
    cityName: "Cà Mau",
    clsconfirmed: "",
    clsdeaths: "",
    confirmed: 38,
    incconfirmed: 0,
    recovered: 7,
    deaths: 0,
    incdeath: 0,
    onevaccine: 44174,
    donevaccine: 8228,
    onevaccinepercent: 3.7,
    donevaccinepercent: 0.69,
  },
  {
    cityId: "VN-67",
    cityName: "Nam Định",
    clsconfirmed: "",
    clsdeaths: "",
    confirmed: 31,
    incconfirmed: 0,
    recovered: 18,
    deaths: 0,
    incdeath: 0,
    onevaccine: 43091,
    donevaccine: 1647,
    onevaccinepercent: 2.42,
    donevaccinepercent: 0.09,
  },
  {
    cityId: "VN-03",
    cityName: "Hà Giang",
    clsconfirmed: "",
    clsdeaths: "",
    confirmed: 21,
    incconfirmed: 0,
    recovered: 3,
    deaths: 0,
    incdeath: 0,
    onevaccine: 47315,
    donevaccine: 3522,
    onevaccinepercent: 5.54,
    donevaccinepercent: 0.41,
  },
  {
    cityId: "VN-69",
    cityName: "Thái Nguyên",
    clsconfirmed: "",
    clsdeaths: "",
    confirmed: 19,
    incconfirmed: 0,
    recovered: 8,
    deaths: 0,
    incdeath: 0,
    onevaccine: 47396,
    donevaccine: 6603,
    onevaccinepercent: 3.68,
    donevaccinepercent: 0.51,
  },
  {
    cityId: "VN-02",
    cityName: "Lào Cai",
    clsconfirmed: "",
    clsdeaths: "",
    confirmed: 11,
    incconfirmed: 0,
    recovered: 2,
    deaths: 0,
    incdeath: 0,
    onevaccine: 56477,
    donevaccine: 4622,
    onevaccinepercent: 7.73,
    donevaccinepercent: 0.63,
  },
  {
    cityId: "VN-53",
    cityName: "Bắc Kạn",
    clsconfirmed: "",
    clsdeaths: "",
    confirmed: 6,
    incconfirmed: 0,
    recovered: 0,
    deaths: 0,
    incdeath: 0,
    onevaccine: 13072,
    donevaccine: 2011,
    onevaccinepercent: 4.16,
    donevaccinepercent: 0.64,
  },
  {
    cityId: "VN-06",
    cityName: "Yên Bái",
    clsconfirmed: "",
    clsdeaths: "",
    confirmed: 5,
    incconfirmed: 0,
    recovered: 5,
    deaths: 0,
    incdeath: 0,
    onevaccine: 27217,
    donevaccine: 4261,
    onevaccinepercent: 3.31,
    donevaccinepercent: 0.52,
  },
  {
    cityId: "VN-07",
    cityName: "Tuyên Quang",
    clsconfirmed: "",
    clsdeaths: "",
    confirmed: 2,
    incconfirmed: 0,
    recovered: 0,
    deaths: 0,
    incdeath: 0,
    onevaccine: 27005,
    donevaccine: 5845,
    onevaccinepercent: 3.44,
    donevaccinepercent: 0.74,
  },
  {
    cityId: "VN-01",
    cityName: "Lai Châu",
    clsconfirmed: "",
    clsdeaths: "",
    confirmed: 2,
    incconfirmed: 0,
    recovered: 1,
    deaths: 0,
    incdeath: 0,
    onevaccine: 29597,
    donevaccine: 3069,
    onevaccinepercent: 6.43,
    donevaccinepercent: 0.67,
  }
];
